// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {main} from '../models';
import {claims} from '../models';
import {cli} from '../models';
import {modelcatalog} from '../models';
import {database} from '../models';
import {projectmap} from '../models';

export function AddAntiAccountKey(arg1:string,arg2:string):Promise<void>;

export function AddAntiOAuthAccountKey(arg1:string,arg2:string):Promise<void>;

export function AddMCPServer(arg1:services.MCPServer):Promise<services.MCPServer>;

export function ApproveRegressionGuard(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function AssignTask(arg1:string,arg2:string):Promise<void>;

export function BuildJoinCommands(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, string>>;

export function CancelScheduledJob(arg1:string):Promise<void>;

export function CheckChromeDebugMode():Promise<Record<string, any>>;

export function CheckForUpdates():Promise<services.UpdateInfo>;

export function CheckoutGitBranch(arg1:string):Promise<void>;

export function ClaimsHostStatus():Promise<Record<string, any>>;

export function ClearActiveSession(arg1:string):Promise<void>;

export function ClearAllTasks():Promise<void>;

export function CreateChecksFile():Promise<string>;

export function CreateGitBranch(arg1:string):Promise<void>;

export function CreateGitCommit(arg1:string):Promise<void>;

export function CreateTask(arg1:models.Task):Promise<void>;

export function DecomposePlan(arg1:string):Promise<Array<models.Task>>;

export function DecomposePlanWithProvider(arg1:string,arg2:string,arg3:string):Promise<Array<models.Task>>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteAntiAccountKey(arg1:string):Promise<boolean>;

export function DeleteDoneTasks():Promise<void>;

export function DeleteRole(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function DownloadAndUpdate(arg1:string):Promise<main.UpdateResponse>;

export function ExportKanbanReport():Promise<string>;

export function FinishClaimSession(arg1:string):Promise<claims.Outcome>;

export function ForceAdjudicateClaims(arg1:string):Promise<void>;

export function GenerateCommitMessage():Promise<string>;

export function GetActiveSession(arg1:string):Promise<string>;

export function GetAgents():Promise<Array<models.Agent>>;

export function GetAntiAccountKeys():Promise<Array<cli.AntiAccountKey>>;

export function GetAppVersion():Promise<string>;

export function GetAutoApproveAll():Promise<boolean>;

export function GetAvailableModels():Promise<Array<modelcatalog.Model>>;

export function GetBudgetStatus():Promise<main.BudgetStatus>;

export function GetClaimChat(arg1:string):Promise<Array<claims.ChatMessage>>;

export function GetClaimSession(arg1:string):Promise<Record<string, any>>;

export function GetContextPackPreview(arg1:string):Promise<string>;

export function GetDispatchReadiness():Promise<database.DispatchReadiness>;

export function GetGCPOAuthCredentials():Promise<Record<string, string>>;

export function GetGitBranches():Promise<services.GitBranchInfo>;

export function GetGitLog(arg1:number):Promise<Array<services.GitCommitInfo>>;

export function GetGitStatus():Promise<Record<string, any>>;

export function GetGitWatchConfig():Promise<services.GitWatchConfig>;

export function GetIntegrationsConfig():Promise<models.IntegrationsConfig>;

export function GetJobKinds():Promise<Array<string>>;

export function GetMCPCatalogue():Promise<Array<services.MCPServer>>;

export function GetMCPServers():Promise<Array<services.MCPServer>>;

export function GetMaxConcurrency():Promise<number>;

export function GetMemoryConfig():Promise<models.MemoryConfig>;

export function GetMemoryLessons(arg1:string):Promise<Array<models.MemoryLesson>>;

export function GetPipelineSteps():Promise<Array<models.PipelineStep>>;

export function GetProjectGraph():Promise<models.ModuleGraph>;

export function GetProjectMap():Promise<models.ProjectMapStats>;

export function GetProjectMapStaleness():Promise<models.StalenessReport>;

export function GetRegressions():Promise<Array<models.Regression>>;

export function GetRoleContent(arg1:string):Promise<string>;

export function GetScheduledJobs():Promise<Array<services.ScheduledJob>>;

export function GetShowCLIConsole():Promise<boolean>;

export function GetSystemMetrics():Promise<main.SystemMetrics>;

export function GetTaskTimeoutMinutes():Promise<number>;

export function GetTasks():Promise<Array<models.Task>>;

export function GetVerifyBuild():Promise<boolean>;

export function GetWorkspaceConfig():Promise<models.WorkspaceConfig>;

export function GetWorkspaceDiff():Promise<string>;

export function ImportGCPCredentialsFile():Promise<string>;

export function ImportGoogleAccounts(arg1:string):Promise<string>;

export function IsOrchestratorRunning():Promise<boolean>;

export function IsTunnelRunning():Promise<boolean>;

export function IsWebhookRunning():Promise<boolean>;

export function ListRoles():Promise<Array<string>>;

export function OpenAgentChromeWindow(arg1:string):Promise<Record<string, any>>;

export function OpenClaimDebate(arg1:string):Promise<void>;

export function OpenClaimSession(arg1:string,arg2:number):Promise<Record<string, any>>;

export function OpenGoogleOAuthLogin(arg1:string):Promise<string>;

export function OpenURLInBrowser(arg1:string):Promise<void>;

export function PerformAutoUpdate():Promise<cli.RunResult>;

export function Ping():Promise<boolean>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RebuildProjectMap():Promise<projectmap.BuildReport>;

export function RefreshAccountTokens():Promise<number|number>;

export function RefreshAllAntiAccountQuota():Promise<Record<string, any>>;

export function RefreshAntiAccountQuota(arg1:string):Promise<Record<string, any>>;

export function RefreshGeminiModels():Promise<number>;

export function RefreshProjectSummaries():Promise<number>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function ResetAgentsToDefaults():Promise<void>;

export function ResolveApproval(arg1:string,arg2:boolean):Promise<void>;

export function ResolveBrowserAsk(arg1:string,arg2:string):Promise<boolean>;

export function RetryTask(arg1:string):Promise<void>;

export function RevertGitCommit(arg1:string):Promise<void>;

export function ReviewMemoryLesson(arg1:string,arg2:string):Promise<void>;

export function RunBrowserTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean,arg8:number):Promise<services.BrowserActionResult>;

export function RunGitCommand(arg1:Array<string>):Promise<string>;

export function RunPipeline(arg1:Array<models.PipelineStep>):Promise<Array<models.PipelineStep>>;

export function RunQuickCLI(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<cli.RunResult>;

export function SaveAgent(arg1:models.Agent):Promise<void>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SaveGCPOAuthCredentials(arg1:string,arg2:string):Promise<void>;

export function SaveGitWatchConfig(arg1:services.GitWatchConfig):Promise<void>;

export function SaveIntegrationsConfig(arg1:models.IntegrationsConfig):Promise<models.IntegrationsConfig>;

export function SaveMemoryConfig(arg1:models.MemoryConfig):Promise<void>;

export function SaveRoleContent(arg1:string,arg2:string):Promise<void>;

export function SayInClaimSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanWorkspaceFiles():Promise<Array<string>>;

export function ScheduleJob(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<string>;

export function ScheduleKind(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function SchedulePrompt(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SelectGoogleAccountsFile():Promise<string>;

export function SelectWorkspaceFolder():Promise<string>;

export function SetAntiAccountTier(arg1:string,arg2:string):Promise<boolean>;

export function SetAutoApproveAll(arg1:boolean):Promise<boolean>;

export function SetCurrentAntiAccountKey(arg1:string):Promise<boolean>;

export function SetDailyBudgetUSD(arg1:number):Promise<number>;

export function SetMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetMaxConcurrency(arg1:number):Promise<number>;

export function SetOnboardingSeen(arg1:boolean):Promise<boolean>;

export function SetScheduledJobEnabled(arg1:string,arg2:boolean):Promise<boolean>;

export function SetShowCLIConsole(arg1:boolean):Promise<boolean>;

export function SetTaskTimeoutMinutes(arg1:number):Promise<number>;

export function SetVerifyBuild(arg1:boolean):Promise<boolean>;

export function ShouldShowOnboarding():Promise<boolean>;

export function StartClaimsHost(arg1:number):Promise<Record<string, any>>;

export function StartOrchestrator():Promise<boolean>;

export function StartTunnelProcess(arg1:string):Promise<string>;

export function StopBrowserTask():Promise<void>;

export function StopClaimsHost():Promise<void>;

export function StopOrchestrator():Promise<boolean>;

export function StopTask(arg1:string):Promise<boolean>;

export function StopTunnelProcess():Promise<boolean>;

export function TestMCPServer(arg1:string):Promise<string>;

export function ToggleAntiAccountKeyStatus(arg1:string):Promise<string>;

export function ToggleWebhook(arg1:number):Promise<boolean>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<void>;

export function WarmupAntiAccountKeys():Promise<main.WarmupResult>;
