// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {main} from '../models';
import {cli} from '../models';

export function AddAntiAccountKey(arg1:string,arg2:string):Promise<void>;

export function AddAntiOAuthAccountKey(arg1:string,arg2:string):Promise<void>;

export function AssignTask(arg1:string,arg2:string):Promise<void>;

export function CancelScheduledJob(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<services.UpdateInfo>;

export function CheckoutGitBranch(arg1:string):Promise<void>;

export function ClearActiveSession(arg1:string):Promise<void>;

export function ClearAllTasks():Promise<void>;

export function CreateGitBranch(arg1:string):Promise<void>;

export function CreateGitCommit(arg1:string):Promise<void>;

export function CreateTask(arg1:models.Task):Promise<void>;

export function DecomposePlan(arg1:string):Promise<Array<models.Task>>;

export function DecomposePlanWithProvider(arg1:string,arg2:string,arg3:string):Promise<Array<models.Task>>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteDoneTasks():Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function DownloadAndUpdate(arg1:string):Promise<main.UpdateResponse>;

export function ExportKanbanReport():Promise<string>;

export function GetActiveSession(arg1:string):Promise<string>;

export function GetAgents():Promise<Array<models.Agent>>;

export function GetAntiAccountKeys():Promise<Array<cli.AntiAccountKey>>;

export function GetAppVersion():Promise<string>;

export function GetAutoApproveAll():Promise<boolean>;

export function GetGitBranches():Promise<services.GitBranchInfo>;

export function GetGitLog(arg1:number):Promise<Array<services.GitCommitInfo>>;

export function GetGitStatus():Promise<Record<string, any>>;

export function GetIntegrationsConfig():Promise<models.IntegrationsConfig>;

export function ShouldShowOnboarding():Promise<boolean>;

export function SetOnboardingSeen(arg1:boolean):Promise<boolean>;

export function SaveIntegrationsConfig(arg1:models.IntegrationsConfig):Promise<models.IntegrationsConfig>;

export function GetWorkspaceDiff():Promise<string>;

export function RunGitCommand(arg1:Array<string>):Promise<string>;

export function GenerateCommitMessage():Promise<string>;

export function GetMaxConcurrency():Promise<number>;

export function SetVerifyBuild(arg1:boolean):Promise<boolean>;

export function GetVerifyBuild():Promise<boolean>;

export function SetTaskTimeoutMinutes(arg1:number):Promise<number>;

export function GetTaskTimeoutMinutes():Promise<number>;

export function GetPipelineSteps():Promise<Array<models.PipelineStep>>;

export function GetScheduledJobs():Promise<Array<services.ScheduledJob>>;

export function GetShowCLIConsole():Promise<boolean>;

export function GetSystemMetrics():Promise<main.SystemMetrics>;

export function GetTasks():Promise<Array<models.Task>>;

export function GetWorkspaceConfig():Promise<models.WorkspaceConfig>;

export function IsOrchestratorRunning():Promise<boolean>;

export function IsWebhookRunning():Promise<boolean>;

export function OpenGoogleOAuthLogin(arg1:string):Promise<string>;

export function OpenURLInBrowser(arg1:string):Promise<void>;

export function PerformAutoUpdate():Promise<cli.RunResult>;

export function Ping():Promise<boolean>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ResetAgentsToDefaults():Promise<void>;

export function ResolveApproval(arg1:string,arg2:boolean):Promise<void>;

export function RetryTask(arg1:string):Promise<void>;

export function RevertGitCommit(arg1:string):Promise<void>;

export function RunBrowserTask(arg1:string,arg2:boolean):Promise<services.BrowserActionResult>;

export function RunPipeline(arg1:Array<models.PipelineStep>):Promise<Array<models.PipelineStep>>;

export function RunQuickCLI(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<cli.RunResult>;

export function SaveAgent(arg1:models.Agent):Promise<void>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function ScanWorkspaceFiles():Promise<Array<string>>;

export function SchedulePrompt(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SelectWorkspaceFolder():Promise<string>;

export function SetAutoApproveAll(arg1:boolean):Promise<boolean>;

export function SetMaxConcurrency(arg1:number):Promise<number>;

export function SetShowCLIConsole(arg1:boolean):Promise<boolean>;

export function StartOrchestrator():Promise<boolean>;

export function StopOrchestrator():Promise<boolean>;

export function StopTask(arg1:string):Promise<boolean>;

export function ToggleWebhook(arg1:number):Promise<boolean>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<void>;
