// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAllTasks() {
  return window['go']['main']['App']['ClearAllTasks']();
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DecomposePlan(arg1) {
  return window['go']['main']['App']['DecomposePlan'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteDoneTasks() {
  return window['go']['main']['App']['DeleteDoneTasks']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportKanbanReport() {
  return window['go']['main']['App']['ExportKanbanReport']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetPipelineSteps() {
  return window['go']['main']['App']['GetPipelineSteps']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetWorkspaceConfig() {
  return window['go']['main']['App']['GetWorkspaceConfig']();
}

export function IsOrchestratorRunning() {
  return window['go']['main']['App']['IsOrchestratorRunning']();
}

export function IsWebhookRunning() {
  return window['go']['main']['App']['IsWebhookRunning']();
}

export function ResetAgentsToDefaults() {
  return window['go']['main']['App']['ResetAgentsToDefaults']();
}

export function RunPipeline(arg1) {
  return window['go']['main']['App']['RunPipeline'](arg1);
}

export function RunQuickCLI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunQuickCLI'](arg1, arg2, arg3, arg4);
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function ScanWorkspaceFiles() {
  return window['go']['main']['App']['ScanWorkspaceFiles']();
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function StartOrchestrator() {
  return window['go']['main']['App']['StartOrchestrator']();
}

export function StopOrchestrator() {
  return window['go']['main']['App']['StopOrchestrator']();
}

export function ToggleWebhook(arg1) {
  return window['go']['main']['App']['ToggleWebhook'](arg1);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}
