// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {cli} from '../models';

export function CheckForUpdates():Promise<services.UpdateInfo>;

export function ClearAllTasks():Promise<void>;

export function CreateTask(arg1:models.Task):Promise<void>;

export function DecomposePlan(arg1:string):Promise<Array<models.Task>>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteDoneTasks():Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function ExportKanbanReport():Promise<string>;

export function GetAgents():Promise<Array<models.Agent>>;

export function GetPipelineSteps():Promise<Array<models.PipelineStep>>;

export function GetTasks():Promise<Array<models.Task>>;

export function GetWorkspaceConfig():Promise<models.WorkspaceConfig>;

export function IsOrchestratorRunning():Promise<boolean>;

export function IsWebhookRunning():Promise<boolean>;

export function ResetAgentsToDefaults():Promise<void>;

export function RunPipeline(arg1:Array<models.PipelineStep>):Promise<Array<models.PipelineStep>>;

export function RunQuickCLI(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<cli.RunResult>;

export function SaveAgent(arg1:models.Agent):Promise<void>;

export function ScanWorkspaceFiles():Promise<Array<string>>;

export function SelectWorkspaceFolder():Promise<string>;

export function StartOrchestrator():Promise<boolean>;

export function StopOrchestrator():Promise<boolean>;

export function ToggleWebhook(arg1:number):Promise<boolean>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<void>;
