// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAntiAccountKey(arg1, arg2) {
  return window['go']['main']['App']['AddAntiAccountKey'](arg1, arg2);
}

export function AddAntiOAuthAccountKey(arg1, arg2) {
  return window['go']['main']['App']['AddAntiOAuthAccountKey'](arg1, arg2);
}

export function AssignTask(arg1, arg2) {
  return window['go']['main']['App']['AssignTask'](arg1, arg2);
}

export function CancelScheduledJob(arg1) {
  return window['go']['main']['App']['CancelScheduledJob'](arg1);
}

export function CheckChromeDebugMode() {
  return window['go']['main']['App']['CheckChromeDebugMode']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckoutGitBranch(arg1) {
  return window['go']['main']['App']['CheckoutGitBranch'](arg1);
}

export function ClearActiveSession(arg1) {
  return window['go']['main']['App']['ClearActiveSession'](arg1);
}

export function ClearAllTasks() {
  return window['go']['main']['App']['ClearAllTasks']();
}

export function CreateGitBranch(arg1) {
  return window['go']['main']['App']['CreateGitBranch'](arg1);
}

export function CreateGitCommit(arg1) {
  return window['go']['main']['App']['CreateGitCommit'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DecomposePlan(arg1) {
  return window['go']['main']['App']['DecomposePlan'](arg1);
}

export function DecomposePlanWithProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecomposePlanWithProvider'](arg1, arg2, arg3);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteAntiAccountKey(arg1) {
  return window['go']['main']['App']['DeleteAntiAccountKey'](arg1);
}

export function DeleteDoneTasks() {
  return window['go']['main']['App']['DeleteDoneTasks']();
}

export function DeleteRole(arg1) {
  return window['go']['main']['App']['DeleteRole'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function DownloadAndUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndUpdate'](arg1);
}

export function ExportKanbanReport() {
  return window['go']['main']['App']['ExportKanbanReport']();
}

export function GenerateCommitMessage() {
  return window['go']['main']['App']['GenerateCommitMessage']();
}

export function GetActiveSession(arg1) {
  return window['go']['main']['App']['GetActiveSession'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetAntiAccountKeys() {
  return window['go']['main']['App']['GetAntiAccountKeys']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoApproveAll() {
  return window['go']['main']['App']['GetAutoApproveAll']();
}

export function GetGCPOAuthCredentials() {
  return window['go']['main']['App']['GetGCPOAuthCredentials']();
}

export function GetGitBranches() {
  return window['go']['main']['App']['GetGitBranches']();
}

export function GetGitLog(arg1) {
  return window['go']['main']['App']['GetGitLog'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetIntegrationsConfig() {
  return window['go']['main']['App']['GetIntegrationsConfig']();
}

export function GetMaxConcurrency() {
  return window['go']['main']['App']['GetMaxConcurrency']();
}

export function GetPipelineSteps() {
  return window['go']['main']['App']['GetPipelineSteps']();
}

export function GetRoleContent(arg1) {
  return window['go']['main']['App']['GetRoleContent'](arg1);
}

export function GetScheduledJobs() {
  return window['go']['main']['App']['GetScheduledJobs']();
}

export function GetShowCLIConsole() {
  return window['go']['main']['App']['GetShowCLIConsole']();
}

export function GetSystemMetrics() {
  return window['go']['main']['App']['GetSystemMetrics']();
}

export function GetTaskTimeoutMinutes() {
  return window['go']['main']['App']['GetTaskTimeoutMinutes']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetVerifyBuild() {
  return window['go']['main']['App']['GetVerifyBuild']();
}

export function GetWorkspaceConfig() {
  return window['go']['main']['App']['GetWorkspaceConfig']();
}

export function GetWorkspaceDiff() {
  return window['go']['main']['App']['GetWorkspaceDiff']();
}

export function IsOrchestratorRunning() {
  return window['go']['main']['App']['IsOrchestratorRunning']();
}

export function IsWebhookRunning() {
  return window['go']['main']['App']['IsWebhookRunning']();
}

export function ListRoles() {
  return window['go']['main']['App']['ListRoles']();
}

export function OpenAgentChromeWindow(arg1) {
  return window['go']['main']['App']['OpenAgentChromeWindow'](arg1);
}

export function OpenGoogleOAuthLogin(arg1) {
  return window['go']['main']['App']['OpenGoogleOAuthLogin'](arg1);
}

export function OpenURLInBrowser(arg1) {
  return window['go']['main']['App']['OpenURLInBrowser'](arg1);
}

export function PerformAutoUpdate() {
  return window['go']['main']['App']['PerformAutoUpdate']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ResetAgentsToDefaults() {
  return window['go']['main']['App']['ResetAgentsToDefaults']();
}

export function ResolveApproval(arg1, arg2) {
  return window['go']['main']['App']['ResolveApproval'](arg1, arg2);
}

export function ResolveBrowserAsk(arg1, arg2) {
  return window['go']['main']['App']['ResolveBrowserAsk'](arg1, arg2);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function RevertGitCommit(arg1) {
  return window['go']['main']['App']['RevertGitCommit'](arg1);
}

export function RunBrowserTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RunBrowserTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RunGitCommand(arg1) {
  return window['go']['main']['App']['RunGitCommand'](arg1);
}

export function RunPipeline(arg1) {
  return window['go']['main']['App']['RunPipeline'](arg1);
}

export function RunQuickCLI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunQuickCLI'](arg1, arg2, arg3, arg4);
}

export function SaveAgent(arg1) {
  return window['go']['main']['App']['SaveAgent'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SaveGCPOAuthCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveGCPOAuthCredentials'](arg1, arg2);
}

export function SaveIntegrationsConfig(arg1) {
  return window['go']['main']['App']['SaveIntegrationsConfig'](arg1);
}

export function SaveRoleContent(arg1, arg2) {
  return window['go']['main']['App']['SaveRoleContent'](arg1, arg2);
}

export function ScanWorkspaceFiles() {
  return window['go']['main']['App']['ScanWorkspaceFiles']();
}

export function SchedulePrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SchedulePrompt'](arg1, arg2, arg3);
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function SetAutoApproveAll(arg1) {
  return window['go']['main']['App']['SetAutoApproveAll'](arg1);
}

export function SetCurrentAntiAccountKey(arg1) {
  return window['go']['main']['App']['SetCurrentAntiAccountKey'](arg1);
}

export function SetMaxConcurrency(arg1) {
  return window['go']['main']['App']['SetMaxConcurrency'](arg1);
}

export function SetOnboardingSeen(arg1) {
  return window['go']['main']['App']['SetOnboardingSeen'](arg1);
}

export function SetShowCLIConsole(arg1) {
  return window['go']['main']['App']['SetShowCLIConsole'](arg1);
}

export function SetTaskTimeoutMinutes(arg1) {
  return window['go']['main']['App']['SetTaskTimeoutMinutes'](arg1);
}

export function SetVerifyBuild(arg1) {
  return window['go']['main']['App']['SetVerifyBuild'](arg1);
}

export function ShouldShowOnboarding() {
  return window['go']['main']['App']['ShouldShowOnboarding']();
}

export function StartOrchestrator() {
  return window['go']['main']['App']['StartOrchestrator']();
}

export function StopBrowserTask() {
  return window['go']['main']['App']['StopBrowserTask']();
}

export function StopOrchestrator() {
  return window['go']['main']['App']['StopOrchestrator']();
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function ToggleAntiAccountKeyStatus(arg1) {
  return window['go']['main']['App']['ToggleAntiAccountKeyStatus'](arg1);
}

export function ToggleWebhook(arg1) {
  return window['go']['main']['App']['ToggleWebhook'](arg1);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}

export function WarmupAntiAccountKeys() {
  return window['go']['main']['App']['WarmupAntiAccountKeys']();
}
